services:
  copypasta:
    image: nerwander/copypasta:latest
    container_name: copypasta
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - APP_USERNAME=user
      - APP_PASSWORD=password
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    volumes:
      - copypasta_data:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  copypasta_data:
    driver: local
